# Generated by Django 5.2.6 on 2025-09-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteAppearance',
        ),
        migrations.AlterModelOptions(
            name='stay',
            options={},
        ),
        migrations.RemoveField(
            model_name='stay',
            name='cost_usd',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='hookups',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='stay',
            name='city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='stay',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stay',
            name='state',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
