# Generated by Django 5.2.6 on 2025-09-20 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0002_delete_siteappearance_alter_stay_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='electric_30a',
            field=models.BooleanField(default=False, help_text='30 Amp electric'),
        ),
        migrations.AddField(
            model_name='stay',
            name='electric_50a',
            field=models.BooleanField(default=False, help_text='50 Amp electric'),
        ),
        migrations.AddField(
            model_name='stay',
            name='is_background',
            field=models.BooleanField(default=False, help_text='If true, this photo is used as the site background.'),
        ),
        migrations.AddField(
            model_name='stay',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='stays/'),
        ),
        migrations.AddField(
            model_name='stay',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1 (worst) to 5 (best)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='stay',
            name='sewer_hookup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stay',
            name='water_hookup',
            field=models.BooleanField(default=False),
        ),
    ]
