version: '3.9'
services:
  web:
    build: .
    ports:
      - '8000:8000'
    environment:
      DJANGO_DEBUG: 'false'
      DJANGO_ALLOWED_HOSTS: 'localhost,127.0.0.1'
      DJANGO_CSRF_TRUSTED_ORIGINS: 'http://localhost:8000,http://127.0.0.1:8000'
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
