services:
  - type: web
    name: traveler-web
    runtime: python
    plan: free
    region: oregon
    pythonVersion: 3.12
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    preDeployCommand: |
      python manage.py migrate --noinput
    startCommand: python -m gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1,[::1]"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: traveler-db
          property: connectionString

databases:
  - name: traveler-db
    plan: free
    databaseName: traveler
    user: traveler
