# Generated by Django 5.2.6 on 2025-09-20 17:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0004_stay_electric_extra_stay_price_night'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='city',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='electric_30a',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='electric_50a',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='electric_extra',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='is_background',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='sewer_hookup',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='state',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='water_hookup',
        ),
        migrations.AddField(
            model_name='stay',
            name='check_in',
            field=models.DateField(blank=True, null=True, verbose_name='Check in'),
        ),
        migrations.AddField(
            model_name='stay',
            name='city_state',
            field=models.CharField(blank=True, max_length=120, verbose_name='City/St'),
        ),
        migrations.AddField(
            model_name='stay',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Fees'),
        ),
        migrations.AddField(
            model_name='stay',
            name='leave_date',
            field=models.DateField(blank=True, null=True, verbose_name='Leave'),
        ),
        migrations.AddField(
            model_name='stay',
            name='nights',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='#Nts'),
        ),
        migrations.AddField(
            model_name='stay',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='stay',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid?'),
        ),
        migrations.AddField(
            model_name='stay',
            name='park',
            field=models.CharField(default=' ', max_length=200, verbose_name='Park'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stay',
            name='site',
            field=models.CharField(blank=True, max_length=20, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='stay',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='price_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Rate/nt'),
        ),
    ]
