# Generated by Django 5.2.6 on 2025-09-20 20:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0005_remove_stay_city_remove_stay_electric_30a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='city_state',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='nights',
        ),
        migrations.AddField(
            model_name='stay',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='stay',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='stays_photos/'),
        ),
        migrations.AddField(
            model_name='stay',
            name='state',
            field=models.CharField(blank=True, default='', help_text='2-letter code', max_length=2),
        ),
        migrations.AlterField(
            model_name='stay',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stay',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stay',
            name='leave_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stay',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='stay',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stay',
            name='park',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stay',
            name='price_night',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='stay',
            name='site',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stay',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True),
        ),
    ]
