# Generated by Django 5.2.6 on 2025-09-21 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0009_add_lat_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='longitude',
        ),
    ]
