# Generated by Django 5.2.6 on 2025-09-22 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0010_add_lat_lng_fix'),
        ('stays', '0011_force_add_lat_lng'),
    ]

    operations = [
    ]
