# Generated by Django 5.2.6 on 2025-09-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0012_merge_0010_add_lat_lng_fix_0011_force_add_lat_lng'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stay',
            options={'ordering': ['-check_in']},
        ),
        migrations.RenameField(
            model_name='stay',
            old_name='leave_date',
            new_name='leave',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='price_night',
        ),
        migrations.AddField(
            model_name='stay',
            name='elect_extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stay',
            name='nights',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='rate_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stay',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stay',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stay',
            name='park',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stay',
            name='site',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stay',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stay',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
