# Generated by Django 5.2.6 on 2025-09-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0013_alter_stay_options_rename_leave_date_stay_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stay',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
