# Generated by Django 5.2.6 on 2025-09-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0003_stay_electric_30a_stay_electric_50a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='electric_extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stay',
            name='price_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
